import { test, expect } from '@playwright/test';
test('static preview works under the project path without backend or browser storage', async ({ page }) => {
  const errors: string[] = [], unexpected: string[] = [];
  page.on('pageerror', e => errors.push(e.message));
  page.on('request', r => { if (!r.url().startsWith('http://127.0.0.1:3099/jarvis/')) unexpected.push(r.url()); });
  await page.goto('./');
  await expect(page.getByRole('region', {name:'Preview information'})).toBeVisible();
  await expect(page.locator('input[type=password]')).toHaveCount(0);
  const send = async (text: string) => { await page.getByLabel('Ask JARVIS').fill(text); await page.getByRole('button',{name:'Send command'}).click(); };
  await send('add task <img src=x onerror=alert(1)>');
  await expect(page.getByRole('button',{name:'Complete <img src=x onerror=alert(1)>',exact:true})).toBeVisible();
  await page.getByRole('button',{name:'Delete <img src=x onerror=alert(1)>',exact:true}).click();
  await send('timer 2 seconds');
  await expect(page.locator('.notice').filter({hasText:'2 seconds timer'})).toBeVisible({timeout:10000});
  await page.getByRole('button',{name:'Open sensor simulator'}).click();
  await page.getByRole('button',{name:'occupied',exact:true}).click();
  await expect(page.locator('.simulation')).toContainText('Test room: occupied');
  await page.getByRole('button',{name:'Controls',exact:true}).click();
  await page.getByRole('button',{name:'Pause actions & delivery',exact:true}).click();
  await page.getByLabel('Change',{exact:true}).selectOption('resume');
  await page.getByRole('button',{name:'Apply change'}).click();
  await page.getByRole('button',{name:'Controls',exact:true}).click();
  await page.getByLabel('Change',{exact:true}).selectOption('revoke');
  await page.getByRole('button',{name:'Apply change'}).click();
  await expect(page.getByRole('button',{name:'Complete Explore your JARVIS workspace',exact:true})).toHaveCount(0);
  await page.getByRole('button',{name:'Controls',exact:true}).click();
  await page.getByLabel('Change',{exact:true}).selectOption('grant');
  await page.getByRole('button',{name:'Apply change'}).click();
  await send('add task Reset check');
  await expect(page.getByRole('button',{name:'Complete Reset check',exact:true})).toBeVisible();
  await page.getByRole('button',{name:'Reset demo',exact:true}).click();
  await expect(page.getByRole('button',{name:'Complete Reset check',exact:true})).toHaveCount(0);
  await expect(page.getByRole('button',{name:'Complete Explore your JARVIS workspace',exact:true})).toBeVisible();
  await page.screenshot({path:'artifacts/pages-desktop.png',fullPage:true});
  await page.setViewportSize({width:390,height:844});
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
  expect(await page.evaluate(()=>[localStorage.length,sessionStorage.length])).toEqual([0,0]);
  await page.screenshot({path:'artifacts/pages-mobile.png',fullPage:true});
  for (const width of [320, 768, 1024]) {
    await page.setViewportSize({width,height:900});
    expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
    await expect(page.getByLabel('Ask JARVIS')).toBeVisible();
    await expect(page.getByRole('button',{name:'Controls',exact:true})).toBeVisible();
  }
  await expect(page.locator('.core-display')).toHaveAttribute('aria-hidden','true');
  expect(unexpected).toEqual([]); expect(errors).toEqual([]);
});
