import { test, expect } from '@playwright/test';
import { mkdirSync } from 'node:fs';
const password = 'Synthetic browser passphrase 5729';
test('local browser workflow: enrollment, inert titles, reminders, pause, scopes, responsive layout and lock', async ({ page }) => {
  const errors: string[] = []; const external: string[] = [];
  page.on('pageerror', error => errors.push(error.message));
  await page.route('**/*', route => {
    if (!route.request().url().startsWith('http://127.0.0.1:3098/')) { external.push(route.request().url()); return route.abort(); }
    return route.continue();
  });
  mkdirSync('artifacts', { recursive: true });
  await page.goto('/');
  await expect(page.getByRole('heading', { name: 'Make yourself at home.' })).toBeVisible();
  await page.screenshot({ path: 'artifacts/entry-desktop.png', fullPage: true });
  await page.getByLabel('Setup code').fill('synthetic-browser-setup');
  await page.getByLabel('Password', { exact: true }).fill(password);
  await page.getByRole('checkbox').check();
  await page.getByRole('button', { name: 'Create workspace' }).click();
  await expect(page.getByRole('heading', { name: 'Ready when you are.' })).toBeVisible();
  await page.getByLabel('Task title').fill('Review the JARVIS local alpha');
  await page.locator('.task-form').getByRole('button', { name: 'Add', exact: true }).click();
  await expect(page.locator('.item').getByText('Review the JARVIS local alpha', { exact: true })).toBeVisible();
  await page.getByLabel('Ask JARVIS').fill('timer 2 seconds');
  await page.getByRole('button', { name: 'Send command' }).click();
  await expect(page.locator('.notice').getByText('2 seconds timer', { exact: true })).toBeVisible({ timeout: 10000 });
  await page.getByRole('button', { name: 'Dismiss 2 seconds timer' }).click();
  await expect(page.locator('.notice')).toHaveCount(0);
  await page.getByLabel('Ask JARVIS').fill('timer 25 minutes');
  await page.getByRole('button', { name: 'Send command' }).click();
  await expect(page.locator('.timer-row').getByText('25 minutes timer', { exact: true })).toBeVisible();
  await page.reload();
  await expect(page.locator('.item').getByText('Review the JARVIS local alpha', { exact: true })).toBeVisible();
  await page.getByRole('button', { name: 'Cancel 2 seconds timer', exact: true }).click();
  await page.getByRole('button', { name: 'Open sensor simulator' }).click();
  await page.getByRole('button', { name: 'occupied', exact: true }).click();
  await expect(page.locator('.simulation')).toContainText('Test room: occupied');
  await page.getByRole('button', { name: 'Hide sensor simulator' }).click();
  await page.evaluate(() => scrollTo(0, 0));
  await page.screenshot({ path: 'artifacts/workspace-desktop.png', fullPage: true });
  // Literal markup stays text; no browser HTML interpretation.
  await page.getByLabel('Task title').fill('<img src=x onerror=alert(1)>');
  await page.locator('.task-form').getByRole('button', { name: 'Add', exact: true }).click();
  await expect(page.locator('.item').getByText('<img src=x onerror=alert(1)>', { exact: true })).toBeVisible();
  await expect(page.locator('.item img')).toHaveCount(0);
  await page.getByRole('button', { name: 'Delete <img src=x onerror=alert(1)>', exact: true }).click();
  // Pick the next spring transition so this scenario remains usable next year.
  const current = new Date(); let year = current.getUTCFullYear();
  const marchSunday = (y: number) => { const d = new Date(Date.UTC(y, 2, 31)); d.setUTCDate(31 - d.getUTCDay()); return d; };
  if (marchSunday(year).getTime() <= Date.now() + 86_400_000) year++;
  const springDay = marchSunday(year).toISOString().slice(0, 10);
  await page.getByLabel('Task title').fill('Morning stretch');
  await page.getByLabel('Reminder start', { exact: true }).fill(`${springDay}T01:30`);
  await page.getByLabel('Reminder time zone').fill('Europe/Dublin');
  await page.getByLabel('Repeat', { exact: true }).selectOption('daily');
  await expect(page.locator('.task-form').getByRole('button', { name: 'Add', exact: true })).toBeDisabled();
  await page.getByRole('button', { name: 'Preview reminder times' }).click();
  await expect(page.getByRole('status', { name: 'Reminder preview' })).toContainText(`${springDay} 02:00`);
  await expect(page.getByRole('status', { name: 'Reminder preview' })).toContainText('UTC+01:00');
  await page.getByLabel('Missing time policy').selectOption('skip');
  await expect(page.getByRole('status', { name: 'Reminder preview' })).toHaveCount(0);
  await expect(page.locator('.task-form').getByRole('button', { name: 'Add', exact: true })).toBeDisabled();
  await page.getByLabel('Missing time policy').selectOption('next-valid');
  await page.getByRole('button', { name: 'Preview reminder times' }).click();
  await expect(page.getByRole('status', { name: 'Reminder preview' })).toBeVisible();
  await page.setViewportSize({ width: 390, height: 844 });
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  await page.locator('.schedule-options').screenshot({ path: 'artifacts/schedule-mobile.png' });
  await page.setViewportSize({ width: 1440, height: 1000 });
  await page.locator('.task-form').getByRole('button', { name: 'Add', exact: true }).click();
  await expect(page.locator('.item').filter({ hasText: 'Morning stretch' })).toContainText('daily');
  await page.reload();
  await expect(page.getByRole('button', { name: 'Stop repeating Morning stretch' })).toBeVisible();
  await page.getByRole('button', { name: 'Stop repeating Morning stretch' }).click();
  await expect(page.locator('.item').filter({ hasText: 'Morning stretch' })).toContainText('Completed');
  await page.getByRole('button', { name: 'Controls', exact: true }).click();
  const dialog = page.getByRole('dialog');
  await dialog.getByRole('button', { name: 'Pause actions & delivery' }).click();
  await expect(dialog.getByRole('button', { name: 'Pause actions & delivery' })).toBeDisabled();
  await dialog.getByLabel('Confirm with your password').fill(password);
  await dialog.getByLabel('Change', { exact: true }).selectOption('resume');
  await dialog.getByRole('button', { name: 'Apply change' }).click();
  await expect(dialog).not.toBeVisible();
  await page.getByRole('button', { name: 'Controls', exact: true }).click();
  await dialog.getByLabel('Confirm with your password').fill(password);
  await dialog.getByLabel('Change', { exact: true }).selectOption('revoke');
  await dialog.getByRole('button', { name: 'Apply change' }).click();
  await expect(page.getByText('Review the JARVIS local alpha', { exact: true })).toHaveCount(0);
  await page.getByRole('button', { name: 'Controls', exact: true }).click();
  await dialog.getByLabel('Confirm with your password').fill(password);
  await dialog.getByLabel('Change', { exact: true }).selectOption('grant');
  await dialog.getByRole('button', { name: 'Apply change' }).click();
  await expect(page.locator('.item').getByText('Review the JARVIS local alpha', { exact: true })).toBeVisible();
  await page.setViewportSize({ width: 390, height: 844 });
  await expect(page.getByRole('button', { name: 'Controls', exact: true })).toBeVisible();
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  await page.evaluate(() => scrollTo(0, 0));
  await page.screenshot({ path: 'artifacts/workspace-mobile.png', fullPage: true });
  await page.setViewportSize({ width: 1440, height: 1000 });
  await page.getByRole('button', { name: 'Lock workspace' }).click();
  await expect(page.getByRole('heading', { name: 'Welcome back.' })).toBeVisible();
  await expect(page.getByText('Review the JARVIS local alpha', { exact: true })).toHaveCount(0);
  const state = await page.evaluate(() => ({ local: localStorage.length, session: sessionStorage.length }));
  expect(state).toEqual({ local: 0, session: 0 });
  expect(errors).toEqual([]); expect(external).toEqual([]);
});
